Refatoramento
esterbyte/market_list pull request #7
Opened 2023-11-01 19:50 UTC by esterbyte

2023-11-01 20:32 UTC, pbressan13 requested changes
No model `app/models/market_item.rb`, a quantidade está que precisa ser maior ou igual a 0.

Ajustar, pra que ela seja **APENAS** maior do que 0

2023-11-01 20:32 UTC, pbressan13 commented on app/controllers/market_items_controller.rb
>      @market_list = MarketList.find(params[:market_list_id])
Esse comando se repete no `new`, `create`, `show`, etc.

Será que não conseguimos abstrair isso para um método privado, e depois usar o filter de `:before_action`?

2023-11-01 20:32 UTC, pbressan13 commented on app/controllers/market_lists_controller.rb
>      @market_lists = MarketList.all
Aqui seria legal ao invés também de mostrar todos os MarketList, ordenar eles por ordem descendente, ou seja, sempre mostrar o que tem o market_date mais recente

2023-11-01 20:32 UTC, pbressan13 commented on app/controllers/market_lists_controller.rb
>      @market_list = MarketList.find(params[:id])
Esse método também se repete no `update`, `show`, será que não podemos abstrair para uma função privada e usar um filter de `before_action` também?

2023-11-02 19:26 UTC, esterbyte commented on app/controllers/market_items_controller.rb
>      @market_list = MarketList.find(params[:market_list_id])
adressados!

2023-11-02 19:46 UTC, esterbyte commented on app/controllers/market_lists_controller.rb
>      @market_lists = MarketList.all
adressado!

2023-11-02 20:12 UTC, esterbyte commented on app/controllers/market_lists_controller.rb
>      @market_list = MarketList.find(params[:id])
addressado!

2023-11-06 16:36 UTC, pbressan13 requested changes

2023-11-06 16:36 UTC, pbressan13 commented on app/controllers/market_items_controller.rb
> +  def set_market_item
O nome do método é `set_market_item`, mas está configurando o `market_list`

É melhor mudar o nome para quem ver, entender o que ele está exatamente fazendo, algo como `market_list` ou `set_market_list`

2023-11-06 16:36 UTC, pbressan13 commented on app/controllers/market_items_controller.rb
>      @market_item = @market_list.market_items.find(params[:id])
Esse método também se repete no destroy e show, será que não podemos fazer a mesma coisa, e criar um método privado pra ele com o filter também?

2023-11-06 16:36 UTC, pbressan13 commented on app/controllers/market_items_controller.rb
> +  before_action :set_market_item, only: [:new, :create, :show, :destroy]
Era exatamente isso que eu pensei. Muito bom!

2023-11-06 16:36 UTC, pbressan13 commented on app/models/market_item.rb
> +  validates :quantidade, presence: true, numericality: { only_integer: true, greater_than: 0 }
🚀

2023-11-06 20:18 UTC, pbressan13 approved these changes
Muito bom, por mim atendeu tudo!

2023-11-07 21:43 UTC, merged