Flash messages e Bootstrap
esterbyte/market_list pull request #8
Opened 2023-11-08 19:16 UTC by esterbyte

2023-11-08 20:04 UTC, gprado-justworks approved these changes
⭐  good job Padawan

2023-11-09 19:47 UTC, pbressan13 commented on app/controllers/market_items_controller.rb
> +      flash[:error] = failed_destroy_message
Pode parecer alguma coisa aqui na minha máquina, mas as mensagens de flash estão vindo com atraso (não na hora que dá o erro)

2023-11-09 19:48 UTC, pbressan13 commented on app/views/layouts/application.html.erb
> +        <%= message %>
Depois da mensagem, seria bom incluir um botão de dismiss, para poder fechar a flash message

2023-11-15 21:26 UTC, pbressan13 requested changes

2023-11-15 21:26 UTC, pbressan13 commented on app/views/market_lists/index.html.erb
> -      <%= link_to 'Editar', edit_market_list_path(list) %>
Pelo que eu vi, o nosso código do addEventListener está impactando no modo delete
Acho melhor virar tudo pra button, pra gente não perder mais tempo com isso

```
<ul class="list-unstyled">
  <% @market_lists.each do |list| %>
    <li class="d-flex align-items-center mb-2">
      <span class="mr-2">
        <%= "#{list.name} #{list.market_date}" %>
      </span>
      <%= button_to 'Editar', edit_market_list_path(list), class: 'btn btn-secondary mr-2' %>
      <%= button_to 'Excluir', list, method: :delete, data: { turbo_confirm: 'Tem certeza de que deseja excluir este item?' }, class: 'btn btn-danger mr-2' %>
      <%= button_to 'Ver itens', list, class: 'btn btn-secondary' %>
    </li>
  <% end %>
</ul>
```

2023-11-16 17:32 UTC, esterbyte commented on app/views/market_lists/index.html.erb
> -      <%= link_to 'Editar', edit_market_list_path(list) %>
addressado

2023-11-16 17:32 UTC, merged